apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dev
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "postgres-dev"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresDB }}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.storageClassName }}"
        resources:
          requests:
            storage: "{{ .Values.storageSize }}"