apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-dev
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-dev
  template:
    metadata:
      labels:
        app: rabbitmq-dev
      namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5672
            - containerPort: 15672 # Management UI
          env:
            - name: RABBITMQ_ENABLED_PLUGINS
              value: rabbitmq_management
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmqUsername }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitmqPassword }}"
  serviceName: "rabbitmq-dev"
  volumeClaimTemplates:
    - metadata:
        name: rmq-data
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.storageClassName }}"
        resources:
          requests:
            storage: "{{ .Values.storageSize }}"
