name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches: [main] # Or your main branch, adjust as needed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: Azure/setup-helm@v3
        with:
          version: 'latest' # Or specify a specific Helm version

      - name: Package Helm chart
        run: helm package ./charts/*

      - name: Generate Helm chart index
        run: |
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: . # Deploy the current directory (where index.yaml and chart.tgz are now)
          clean: true # IMPORTANT: This will remove existing files in gh-pages to overwrite