#name: Validate Helm Charts
#
#on:
#  pull_request:
#  push:
#    branches:
#      - main
#
#jobs:
#  validate:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Helm
#        uses: azure/setup-helm@v3
#
#      - name: Set up kubeconform
#        run: |
#          curl -sSLf https://github.com/instrumenta/kubeconform/releases/download/v0.6.0/kubeconform_Linux_x86_64.tar.gz | tar -xz
#          sudo mv kubeconform /usr/local/bin/
#
#      - name: Lint Helm charts
#        run: |
#          for chart in charts/*; do
#            helm lint "$chart"
#          done
#
#      - name: Template and validate manifests
#        run: |
#          for chart in charts/*; do
#            helm template "$chart" | kubeconform -strict
#          done
#
#      - name: Chart testing.
#        uses: helm/chart-testing-action@v2.7.0